### ISSUE TITLE
Drag and dropping tab hides directory

### ISSUE THREAD

**Issue by rugk** [paulpflug/foldername-tabs#7] opened 2016-01-24 11:40 UTC
Sometimes when you drag and drop a tab to another position the folder name gets "lost", which means it just disappears.

package v0.1.6 
Atom 1.4.0

**Comment by paulpflug** [comment] 2016-01-28 17:32
duplicate of #1 (should be fixed in 0.1.7)

**Closed as completed by paulpflug** 2016-01-28 17:32 UTC
